### ISSUE TITLE
Ruby 2.0-rc2 causes any pry session when this gem is installed to hang immediately

### ISSUE THREAD

**Issue by crazymykl** [pry/pry-exception_explorer#17]
Using `pry` with `binding_of_caller-0.6.9pre3`, `debug_inspector-0.0.2`, and `pry-0.9.12` works.

If this gem is installed, the `pry` executable will become unresponsive on launch and completely utilize its core until it catches `SIGKILL`. Same behavior if instead pry is loaded via 

``` ruby
require 'pry'
Pry::pry
```

**Comment by banister** [comment]
thanks. 2.0 is not yet supported, btw, you should probably switch to the [pry-rescue](https://github.com/conradirwin/pry-rescue) project instead, it does the same thing as PEE but a bit more thoroughly.

**Comment by MSch** [comment]
I can confirm this.

**Comment by kyrylo** [comment]
@MSch, you can confirm what?

**Comment by MSch** [comment]
@kyrylo the original issue.

**Comment by josephlord** [comment]
I've just lost some time to this.  Could a warning/error be issued for incompatible Ruby versions even if the crash can't be prevented?  I didn't know the cause was this rather than basic pry or another Gem.

**Comment by banister** [comment]
@josephlord sorry, this gem has been deprecated in favor of [pry-rescue](https://github.com/conradirwin/pry-rescue).  I indicate that on the [README](https://github.com/pry/pry-exception_explorer/blob/master/README.md). Sorry.
